labeling:
  abstain: -1
  lfs:
  - keywords:
    - good
    - excellent
    - amazing
    label: 1
    name: keyword_positive
    type: keyword
  - keywords:
    - bad
    - terrible
    - awful
    label: 0
    name: keyword_negative
    type: keyword
