labeling:
  abstain: -1
  lfs:
  - keywords:
    - excellent
    - outstanding
    - magnificent
    - brilliant
    label: 1
    name: strong_positive
    type: keyword
  - keywords:
    - terrible
    - horrible
    - disgusting
    - pathetic
    label: 0
    name: strong_negative
    type: keyword
