drl_model_path: models/improved_wass_drl.pth
enabled_schedulers:
- FIFO
output_dir: "results/direct_test_\u7F29\u5C0F\u7B97\u529B_FIFO"
platform_file: test_platform_reduced.xml
rag_config_path: configs/rag.yaml
repetitions: 1
workflow_dir: workflows
workflow_sizes:
- 5
