experiment_name: demo_wass_pipeline
random_seed: 42
include:
  - data.yaml
  - labeling.yaml
  - label_model.yaml
  - graph.yaml
  - rag.yaml
  - drl.yaml
  - eval.yaml
paths:
  data_dir: data/
  results_dir: results/demo_wass_pipeline/
