# configs/workflow_config.yaml

ccr: 1.0
large_sizes:
- 200
- 500
medium_sizes:
- 50
- 100
patterns:
- montage
- highly_parallel
random_seed: 42
small_sizes:
- 5
- 10
- 15
- 20
workflow_dir: workflows

experiment_workflows:
  montage:
    sizes: [20]
    count: 2
    seed_start: 100
  highly_parallel:
    sizes: [20]
    count: 2
    seed_start: 100

training_workflows:
  montage:
    sizes: [20] 
    count: 2
    seed_start: 100
  highly_parallel:
    sizes: [20] 
    count: 2
    seed_start: 100